spring.datasource.url=jdbc:h2:file:/home/ubuntu/app/backend/data/testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.sql.init.mode=never

logging.level.org.springframework.jdbc.core.JdbcTemplate=INFO
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=INFO

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:3600000}

server.address=127.0.0.1
server.port=8080